name: General Jobs

on:
  push:
    branches: ['main']

jobs:
  general:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install

      - name: lint
        run: yarn lint

      - name: Start server
        run: |
          yarn dev &

          npx wait-on http://localhost:5173
        env:
          CYPRESS_baseUrl: http://localhost:5173

      - name: Run Cypress Tests
        run: yarn cypress
        env:
          CYPRESS_baseUrl: http://localhost:5173
